from typing import Any

INTER_NEAREST: int

def VideoWriter_fourcc(*args: Any, **kwargs: Any) -> int: ...

class VideoWriter:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def write(self, frame: Any) -> None: ...
    def release(self) -> None: ...

def resize(src: Any, dsize: Any, interpolation: Any = ...) -> Any: ...
