"""Type stubs for pufferlib - all types as Any for now."""

from typing import Any

__version__: str

def namespace(name: str) -> Any: ...
def version() -> str: ...

class PufferEnv:
    """Base PufferEnv class."""
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def reset(self, *args: Any, **kwargs: Any) -> Any: ...
    def step(self, *args: Any, **kwargs: Any) -> Any: ...
    def close(self) -> None: ...

# Re-export emulation module
from . import emulation as emulation
