"""Type stubs for pufferlib.emulation - all types as Any for now."""

from typing import Any

class GymnasiumPufferEnv:
    """Gymnasium PufferEnv wrapper."""
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def reset(self, *args: Any, **kwargs: Any) -> Any: ...
    def step(self, *args: Any, **kwargs: Any) -> Any: ...
    def close(self) -> None: ...

class GymPufferEnv:
    """Gym PufferEnv wrapper."""
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def reset(self, *args: Any, **kwargs: Any) -> Any: ...
    def step(self, *args: Any, **kwargs: Any) -> Any: ...
    def close(self) -> None: ...
